sudo: required
services:
  - docker

before_install:
  - docker build -t martijntoonen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true martijntoonen/docker-react npm run test

language: generic